#!/usr/bin/env node

// imports
var app = require('../app');
var argv = require('optimist').argv;
var portfinder = require('portfinder');
var logger = require('../logger');

// app vars
var port = argv.p;
var host = argv.a || '0.0.0.0';
var log = (argv.s || argv.silent) ? function () {} : logger.info;
var listen = function(port) {
    app.listen(port, host, function() {
        log('Starting up app, serving '.yellow + host.cyan + ' on port: '.yellow + port.toString().cyan);
        log('Hit CTRL-C to stop the server');
    });
};

if (argv.h || argv.help) {
    logger.info([
        'usage: http-server [path] [options]',
        '',
        'options:',
        '  -p                 Port to use [8080]',
        '  -a                 Address to use [0.0.0.0]',
        '  -h --help          Print this list and exit.',
    ].join('\n'));
    process.exit();
}

if (!argv.p) {
    portfinder.basePort = 8080;
    portfinder.getPort(function (err, port) {
        if (err) {
            throw err;
        }
        listen(port);
    });
} else {
    listen(port);
}
